// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-_KqGf1XtQwTTI76JvdzTNLNjscODmQ',
    appId: '1:249755048954:web:46bb86fc7c3318c2e0e243',
    messagingSenderId: '249755048954',
    projectId: 'penpalotp',
    authDomain: 'penpalotp.firebaseapp.com',
    storageBucket: 'penpalotp.firebasestorage.app',
    measurementId: 'G-6JNVWXY3X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCs1unBCjSZz5GucDLznQzNa15ZKlwI0k',
    appId: '1:615044891317:android:95f62418e15755251274fc',
    messagingSenderId: '615044891317',
    projectId: 'otptesting-71a87',
    storageBucket: 'otptesting-71a87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_MeRrILi0MIVgMCMkoHU56yhEy8-Crk',
    appId: '1:249755048954:ios:0ca3799d673beba1e0e243',
    messagingSenderId: '249755048954',
    projectId: 'penpalotp',
    storageBucket: 'penpalotp.firebasestorage.app',
    iosBundleId: 'com.example.mobilepenpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_MeRrILi0MIVgMCMkoHU56yhEy8-Crk',
    appId: '1:249755048954:ios:0ca3799d673beba1e0e243',
    messagingSenderId: '249755048954',
    projectId: 'penpalotp',
    storageBucket: 'penpalotp.firebasestorage.app',
    iosBundleId: 'com.example.mobilepenpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3-_KqGf1XtQwTTI76JvdzTNLNjscODmQ',
    appId: '1:249755048954:web:575a8cc05e3560b5e0e243',
    messagingSenderId: '249755048954',
    projectId: 'penpalotp',
    authDomain: 'penpalotp.firebaseapp.com',
    storageBucket: 'penpalotp.firebasestorage.app',
    measurementId: 'G-TCTBD5JH3B',
  );

}