// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk3ENAKD8I-IfGjg0Y5FXoK0Lwvo8WGvw',
    appId: '1:653298491460:web:32ab73d0ebc14be3bc5c11',
    messagingSenderId: '653298491460',
    projectId: 'email-verification-4abfe',
    authDomain: 'email-verification-4abfe.firebaseapp.com',
    storageBucket: 'email-verification-4abfe.firebasestorage.app',
    measurementId: 'G-TE0PY41FW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyFKXA5FbQHCLf7xP03sNzvz95yO0xhUs',
    appId: '1:653298491460:android:b419fd209b2dbb4fbc5c11',
    messagingSenderId: '653298491460',
    projectId: 'email-verification-4abfe',
    storageBucket: 'email-verification-4abfe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArOw-olXUNVDUMTj-EvdBDRmxj1Dm-nsA',
    appId: '1:653298491460:ios:03f5cfa3ea279776bc5c11',
    messagingSenderId: '653298491460',
    projectId: 'email-verification-4abfe',
    storageBucket: 'email-verification-4abfe.firebasestorage.app',
    iosBundleId: 'com.example.mobilepenpal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArOw-olXUNVDUMTj-EvdBDRmxj1Dm-nsA',
    appId: '1:653298491460:ios:03f5cfa3ea279776bc5c11',
    messagingSenderId: '653298491460',
    projectId: 'email-verification-4abfe',
    storageBucket: 'email-verification-4abfe.firebasestorage.app',
    iosBundleId: 'com.example.mobilepenpal',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZmFmDlVbq7sZGg31JDzJxO8oxVepOGRA',
    appId: '1:580128964866:web:f58a027b515215b1cc421b',
    messagingSenderId: '580128964866',
    projectId: 'analytics-f8d29',
    authDomain: 'analytics-f8d29.firebaseapp.com',
    storageBucket: 'analytics-f8d29.firebasestorage.app',
    measurementId: 'G-WY5NDFXTZL',
  );
}
