// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmFmDlVbq7sZGg31JDzJxO8oxVepOGRA',
    appId: '1:580128964866:web:3ea49d3b6a159d69cc421b',
    messagingSenderId: '580128964866',
    projectId: 'analytics-f8d29',
    authDomain: 'analytics-f8d29.firebaseapp.com',
    storageBucket: 'analytics-f8d29.firebasestorage.app',
    measurementId: 'G-ER7D9KQJZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAQQboEVQS08aroOp4kell7S9wQX-fWk',
    appId: '1:580128964866:android:62d0b764ca94442acc421b',
    messagingSenderId: '580128964866',
    projectId: 'analytics-f8d29',
    storageBucket: 'analytics-f8d29.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAALDTlwSPqPyyDBxkp6QOkNdxtIqkpc18',
    appId: '1:580128964866:ios:067ec9877db5ce3ccc421b',
    messagingSenderId: '580128964866',
    projectId: 'analytics-f8d29',
    storageBucket: 'analytics-f8d29.firebasestorage.app',
    iosBundleId: 'com.example.mobilepenpal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAALDTlwSPqPyyDBxkp6QOkNdxtIqkpc18',
    appId: '1:580128964866:ios:067ec9877db5ce3ccc421b',
    messagingSenderId: '580128964866',
    projectId: 'analytics-f8d29',
    storageBucket: 'analytics-f8d29.firebasestorage.app',
    iosBundleId: 'com.example.mobilepenpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZmFmDlVbq7sZGg31JDzJxO8oxVepOGRA',
    appId: '1:580128964866:web:f58a027b515215b1cc421b',
    messagingSenderId: '580128964866',
    projectId: 'analytics-f8d29',
    authDomain: 'analytics-f8d29.firebaseapp.com',
    storageBucket: 'analytics-f8d29.firebasestorage.app',
    measurementId: 'G-WY5NDFXTZL',
  );
}
