final Map<String, String> enUS = {
  // ===== General =====
  'hello': 'Hello',
  'welcome': 'Welcome',
  'language': 'Language',
  'back': 'Back',
  'next': 'Next',
  'logout': 'Logout',
  'logout_acc': 'Logout of the account',
  'settings': 'Settings',
  'setting': 'Setting',
  'change_language': 'Change Language',
  'dark_mode': 'Dark Mode',
  'loading': 'Loading...',
  'save': 'Save',
  'edit': 'Edit',
  'delete': 'Delete',
  'update': 'Update',
  'create': 'Create',
  'search': 'Search',
  'filter': 'Filter',
  'sort': 'Sort',
  'refresh': 'Refresh',
  'confirm': 'Confirm',
  'confirmed': 'Confirm',
  'continue': 'Continue',
  'done': 'Done',
  'close': 'Close',
  'ok': 'OK',
  'yes': 'Yes',
  'no': 'No',
  'retry': 'Retry',
  'skip': 'Skip',
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'info': 'Information',
  'attention': 'Attention',
  'protection': 'Protection',
  'accuracy': 'Accuracy',
  'best': "Best",
  'need': "Need",
  'scan': 'Scan QR',
  'all': 'All',

  // ===== Authentication =====
  'enter_your_email_or_phone': 'Enter your email or phone number',
  'enter_your_phone_number': 'Enter your phone number',
  'enter_your_password': 'Enter your password',
  'enter_your_school_id': 'Enter your school ID',
  'phone_number': 'Phone Number',
  'account': 'Account',
  'school_id': 'School ID',
  'password': 'Password',
  'forgot_password': 'Forgot Password',
  'login': 'Login',
  'signup': 'Sign Up',
  'register': 'Register',
  'remember_me': 'Remember Me',
  'are_you_sure_you_want_to_logout': 'Are you sure you want to logout?',
  'dont_have_account': "Don't have an account?",
  'already_have_account': 'Already have an account?',
  'account_created_successfully': 'Account created successfully',
  'updated_successfully': "Update Successfully",
  'confirm_password': 'Confirm Password',
  'reset_password': 'Reset Password',
  'change_password': 'Change Password',
  'current_password': 'Current Password',
  'new_password': 'New Password',
  'confirm_new_password': 'Confirm New Password',
  'enter_current_password': 'Enter your current password',
  'enter_new_password': 'Enter new password',
  'confirm_your_new_password': 'Confirm your new password',
  'update_password': 'Update Password',
  'password_updated_successfully': 'Password updated successfully',
  'current_password_required': 'Current password is required',
  'new_password_required': 'New password is required',
  'confirm_password_required': 'Please confirm your new password',
  'already_logged_in_title': 'Account Logged In Elsewhere',
  'already_logged_in_message':
      'This account is currently logged in on another device. Logging in here will log you out from other devices. Do you want to proceed?',

  // ===== OTP Verfication =====
  'otp_verification': 'OTP Verification',
  'enter_verification_code': 'Enter Verification Code',
  'we_sent_code_to': 'We sent a verification code to',
  'didnt_receive_code': "Didn't receive code?",
  'otp_verified_successfully': 'OTP verified successfully',
  'invalid_otp_code': 'Invalid OTP code',
  'verification_failed': 'Verification failed',
  'otp_sent_successfully': "OTP sent successfully",
  'otp_resent_successfully': 'OTP resent successfully',
  'resend': 'Resend',
  'resend_in': 'Resend in',
  'clear': 'Clear',
  'ai_assist': 'AI Assist',
  'verify': 'Verify',

  // ===== Navigation =====
  'home': 'Home',
  'profile': 'Profile',
  'dashboard': 'Dashboard',
  'menu': 'Menu',
  'notifications': 'Notifications',
  'messages': 'Messages',
  'calendar': 'Calendar',
  'reports': 'Reports',
  'history': 'History',
  'help': 'Help',
  'about': 'About',
  'contact': 'Contact',

  // ===== User & Profile =====
  'user': 'User',
  'users': 'Users',
  'name': 'Name',
  'full_name': 'Full Name',
  'first_name': 'First Name',
  'last_name': 'Last Name',
  'email': 'Email',
  'phone': 'Phone',
  'address': 'Address',
  'birthday': 'Birthday',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'other': 'Other',
  'age': 'Age',
  'update_information': 'Update Information',
  'personal_information': 'Personal Information',
  'password_information': 'Password Information',
  'parent_information': 'Parent Information',
  'additional_information': 'Additional Information',
  'enter_first_name': 'Enter first name',
  'enter_last_name': 'Enter last name',
  'enter_nickname': 'Enter nickname',
  'enter_age': 'Enter age',
  'select_gender': 'Select gender',
  'date_of_birth': 'Date of Birth',
  'enter_date_of_birth': 'Enter date of birth',
  'parent_first_name': 'Parent First Name',
  'parent_last_name': 'Parent Last Name',
  'enter_parent_first_name': 'Enter parent first name',
  'enter_parent_last_name': 'Enter parent last name',
  'enter_address': 'Enter address',
  'save_changes': 'Save Changes',
  'no_changes_detected': 'No changes detected',
  'profile_updated_successfully': 'Profile updated successfully',
  'failed_to_update_profile': 'Failed to update profile',
  'an_error_occurred': 'An error occurred',
  'first_name_is_required': 'First name is required',
  'first_name_cannot_exceed_100_characters':
      'First name cannot exceed 100 characters',
  'last_name_cannot_exceed_100_characters':
      'Last name cannot exceed 100 characters',
  'age_must_be_a_number': 'Age must be a number',
  'age_must_be_between_1_and_100': 'Age must be between 1 and 100',
  'gender_must_be_male_or_female': 'Gender must be male or female',
  'failed_to_load_profile': 'Failed to load profile',
  'nickname': 'Nickname',
  'yyyy-mm-dd': 'YYYY-MM-DD',
  'year': 'Year',
  'require_parent_pin': 'Required Parent Pin',

  // ===== Status & Actions =====
  'active': 'Active',
  'inactive': 'Inactive',
  'pending': 'Pending',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'approved': 'Approved',
  'rejected': 'Rejected',
  'submitted': 'Submitted',
  'verified': 'Verified',
  'unverified': 'Unverified',
  'enabled': 'Enabled',
  'disabled': 'Disabled',

  // ===== Time & Date =====
  'today': 'Today',
  'yesterday': 'Yesterday',
  'tomorrow': 'Tomorrow',
  'this_week': 'This Week',
  'this_month': 'This Month',
  'this_year': 'This Year',
  'date': 'Date',
  'time': 'Time',
  'date_time': 'Date & Time',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'due_date': 'Due Date',

  // ===== Numbers & Quantities =====
  'zero': 'Zero',
  'one': 'One',
  'two': 'Two',
  'three': 'Three',
  'four': 'Four',
  'five': 'Five',
  'items': 'Items',
  'item': 'Item',
  'total': 'Total',
  'amount': 'Amount',
  'quantity': 'Quantity',
  'count': 'Count',

  // ===== Error & Success Messages =====
  'invalid_credentials': 'Invalid credentials',
  'email_or_phone_required': 'Email or phone number is required',
  'phone_required': "Phone number is required",
  'invalid_email_or_phone': 'Invalid email or phone number',
  'invalid_phone': 'Invalid phone number',
  'school_id_required': 'School ID is required',
  'school_id_min_2_cha': 'School ID must be at least 2 characters',
  'password_required': 'Password is required',
  'password_min_6_cha': 'Password must be at least 6 characters',
  'passwords_do_not_match': 'Passwords do not match',
  'network_error': 'Network error',
  'server_error': 'Server error',
  'unknown_error': 'Unknown error occurred',
  'try_again': 'Please try again',
  'operation_successful': 'Operation successful',
  'operation_failed': 'Operation failed',
  'data_loaded': 'Data loaded successfully',
  'data_saved': 'Data saved successfully',
  'data_updated': 'Data updated successfully',
  'data_deleted': 'Data deleted successfully',
  'image_updated': "Image updated successfully",
  'image_too_large':
      'Image size is too large. Please choose an image smaller than 2MB',

  // ===== Buttons =====
  'cancel': 'Cancel',
  'submit': 'Submit',
  'add': 'Add',
  'remove': 'Remove',
  'view': 'View',
  'view_all': 'View All',
  'view_details': 'View Details',
  'view_more': 'View More',
  'select': 'Select',
  'choose': 'Choose',
  'browse': 'Browse',
  'upload': 'Upload',
  'download': 'Download',
  'print': 'Print',
  'share': 'Share',

  // ===== Forms & Validation =====
  'required': 'Required',
  'optional': 'Optional',
  'invalid_format': 'Invalid format',
  'field_required': 'This field is required',
  'invalid_email': 'Invalid email address',
  'invalid_url': 'Invalid URL',
  'min_length': 'Must be at least @length characters',
  'max_length': 'Must be at most @length characters',
  'passwords_not_match': 'Passwords do not match',
  'fill_all_fields_correctly': 'Please fill all fields correctly',
  'fill_all_fields': 'Please fill all fields',

  // ===== School Specific =====
  'student': 'Student',
  'teacher': 'Teacher',
  'parent': "Parent",
  'class': 'Class',
  'grade': 'Grade',
  'homework': 'Homework',
  'assignment': 'Assignment',
  'score': 'Score',
  'result': 'Result',
  'my_course': 'My Course',
  'classroom': 'Classroom',
  'no_classroom_yet': 'No classroom yet',
  'join_classroom_desc':
      'Join your child’s classroom to see classmates and progress.',
  'enter_code': 'Enter code',
  'example_code': 'Example: SCH-ABC12345',
  'join': 'Join',
  'joined': 'Joined',
  'children': 'children',
  'classmates': 'Classmates',
  'no_classmates': 'No classmates found',
  "no_course_available": "No course available",
  "pull_down_to_refresh": "Pull down to refresh",

  // ===== Course & Progress =====
  'my_courses': 'My Courses',
  'in_progress': 'In Progress',
  'start': 'Start',
  "locked": 'Locked',
  'level_locked': "This level is locked",
  'subscribe': 'Subscribe',
  'subscription': 'Subscription',
  'subscription_status': 'Subscription Status',
  'plan': 'Plan',
  'free_plan': 'Free Plan',
  'monthly': 'Monthly',
  'yearly': 'Yearly',
  'upgrade_for_more': 'Upgrade for more features',
  'contact_information': 'Contact Information',
  'month': 'month',
  'premium_content': 'Premium Content',
  'premium': "Premium",
  'subscribe_to_unlock': 'Subscribe to unlock this content',
  'progress': 'Progress',
  'lessons': 'lessons',
  'stars': 'Stars',
  'remaining': 'Remaining',
  'course_progress': 'Course Progress',
  'continue_learning': 'Continue Learning',
  'begin_course': 'Begin Course',
  'view_course': 'View Course',
  'course_details': 'Course Details',
  'level': 'Level',
  'stage': 'Stage',
  'exercise': 'Exercise',
  'world': 'World',
  'learning_letters': 'Learning Letters',
  'learning_numbers': 'Learning Numbers',
  'khmer_alphabet': 'Khmer Alphabet',
  'math_practice': 'Math Practice',
  'consonants': 'Consonants',
  'digits': 'Digits',
  'independent_vowels': 'Ind. vowels',
  'dependent_vowels': 'Dep. vowels',

  // ===== Home & Dashboard =====
  'achievements': 'Achievements',
  'streak': 'Streak',
  'time_spent': 'Time Spent',
  'last_played': 'Last Played',
  'current_level': 'Current Level',
  'next_level': 'Next Level',
  'experience_points': 'Experience Points',
  'summary': 'Summary',
  'summary_daily': 'Summary Today',
  'lesson_completed': "Lesson Completed",
  'summary_weekly': 'Summary Weekly',
  'mastered': 'Mastered',
  'review': 'Review',
  'practice_days': 'Practiced Day',

  // ===== Notifications =====
  'no_notifications': 'No Notifications',
  'mark_all_read': 'Mark All as Read',
  'new_assignment': 'New Assignment',
  'achievement_unlocked': 'Achievement Unlocked',
  'level_up': 'Level Up!',

  // ===== Mode Switching =====
  'student_mode': 'Student Mode',
  'parent_mode': 'Parent Mode',
  'switch_to_parent': 'Switch to Parent',
  'switch_to_student': 'Switch to Student',
  'parent_pin': 'Parent PIN',
  'enter_parent_pin': 'Enter Parent PIN',
  'parent_dashboard': 'Parent Dashboard',
  'student_progress': 'Student Progress',

  // ===== PIN / Parent PIN related =====
  'pin': 'PIN',
  'create_pin': 'Create PIN',
  'create_4_digit_pin': 'Create 4-digit PIN',
  'confirm_pin': 'Confirm PIN',
  'confirm_new_pin': 'Confirm new PIN',
  'enter_pin': 'Enter PIN',
  'enter_new_pin': 'Enter new PIN',
  'enter_current_pin': 'Enter current PIN',
  'reenter_pin_to_confirm': 'Re-enter PIN to confirm',
  'pins_do_not_match': 'PINs do not match',
  'invalid_pin': 'Invalid PIN',
  'pin_created': 'PIN created',
  'pin_updated': 'PIN updated',
  'set_pin': 'Set Pin',
  'set_parent_pin_prompt':
      'Would you like to set a 4-digit parent PIN to protect parent mode?',
  'skip_pin_setup': 'Skip PIN setup',
  'dont_ask_again': "Don't ask again",
  'backspace': 'Backspace',
  'enter_digits': 'Please enter 4 digits',
  'update_pin': 'Update PIN',
  'verify_pin': 'Verify PIN',
  'unlock_parent_mode': 'Unlock Parent Mode',
  'success_pin_created': 'Parent PIN has been created successfully',
  'success_pin_updated': 'Parent PIN has been updated successfully',
  'update_parent_pin': 'Update Parent PIN',
  'change_parent_pin': 'Change Parent PIN',
  'enter_current_pin_to_update': 'Enter current PIN to update',
  'create_new_pin': 'Create New PIN',
  'update_parent_pin_title': 'Update Parent PIN',
  'parent_pin_updated': 'Parent PIN updated',
  'parent_pin_created': 'Parent PIN created',
  'pin_setup_complete': 'PIN Setup Complete',
  'pin_verification_successful': 'PIN Verification Successful',
  'enter_4_digit_pin': 'Enter 4-digit PIN',
  're_enter_4_digit_pin': 'Re-enter 4-digit PIN',
  'pin_must_be_4_digits': 'PIN must be 4 digits',
  'pin_changed_successfully': 'PIN changed successfully',
  'current_pin_incorrect': 'Current PIN is incorrect',
  'pin_setup_required': 'PIN setup required',
  'pin_verification_required': 'PIN verification required',
  'create_your_pin': 'Create Your PIN',
  'confirm_your_pin': 'Confirm Your PIN',
  'verify_your_pin': 'Verify Your PIN',

  // ===== QR Scanner =====
  'scan_qr_title': 'Scan QR',
  'flash_on': 'Flash On',
  'flash_off': 'Flash Off',
  'gallery': 'Gallery',
  'align_qr_hint': 'Align the QR inside the frame',
  'no_qr_found': 'No QR code found in that image.',
  'invalid_qr': 'Invalid QR code.',
  'scan_failed': 'Could not scan that image.',
  'flash_unavailable': 'Flashlight is not available on this device.',

  // ===== Report / Parent Report =====
  'report_detail_title': 'Report Details',
  'monthly_summary': 'Monthly Summary',
  'total_exercises': 'Total Exercises',
  'total_study_time': 'Total Study Time',
  'weekly_exercises_in_month': 'Weekly Exercises (This Month)',
  'character_performance': 'Character Performance',
  "no_character_data": "No character data",
  'characters': 'Characters',
  'week': 'Week',
  'attempts': 'Attempts',
  'times': 'times',
  'math': "Math",

  // ===== Summary Page =====
  'summary_perfect': 'Excellent job!',
  'summary_great': 'Great job!',
  'summary_good_try': 'Good try! Keep practicing!',

  // ===== Offline =====
  'offline': 'Offline',
  'no_internet_connection': 'No internet connection',
  'internet_required_to_continue':
      'This app requires an internet connection to continue.\nPlease check your Wi-Fi or mobile data.',
  'open_settings': 'Open Settings',
  'tip_public_wifi_sign_in':
      'Tip: If you’re on public Wi-Fi, you may need to sign in first.',
  'still_offline': 'Still no internet connection.',

  // ===== Stroke Feedback =====
  'feedback_draw_slowly': 'Draw slowly following the guide!',
  'feedback_wrong_count': 'Wrong number of strokes!',
  'feedback_out_of_bounds': "Don't draw outside!",
  'feedback_incomplete': 'Please complete the drawing!',
  'feedback_wrong_direction': 'Wrong direction!',
  'feedback_wrong_order': 'Wrong order!',

  // ===== Praise =====
  'praise_excellent': 'Excellent!',
  'praise_well_done': 'Well done!',

  // ===== Subscription =====
  'school_subscription_title': 'Premium Content',
  'school_subscription_message':
      'This content requires a premium subscription. Please contact your school administrator to activate access for your account.',
  'contact_school_admin': 'Contact School Admin',
  'unlock_unlimited_title': 'Subscribe to unlock more features',
  'unlock_unlimited_subtitle':
      'Get full access to all handwriting levels, AI feedback, and mini-games.',
  'benefit_worlds_title': 'Unlock all lessons',
  'benefit_ai_title': 'Unlock all handwriting with AI',
  'benefit_minigames_title': 'No limit on mini games',
  'subscribe_contact_us': 'Contact us to activate your subscription:',

  // ===== Dynamic Mini Game =====
  'highest_score': 'HIGHEST SCORE',
  'oops': 'Oops!',
  'no_mini_games_available_right_now': 'No mini-games available right now.',
  'ready_to_play': 'Ready to Play?',
  'choose_an_option': 'Choose an Option',
  'choose_your_games': 'CHOOSE YOUR GAMES',
  'deselect_all': 'DESELECT ALL',
  'select_all': 'SELECT ALL',
  'how_to_play': 'HOW TO PLAY',
  'select_a_game_first': 'Select a game first!',
  'start_playing': 'START PLAYING',
  'drawing': 'Drawing',
  'choices': 'Choices',
  'drag': 'Drag',
  'typing': 'Typing',
  'surprise_me': 'Surprise Me!',
  'match_the_pairs': 'Match the pairs 🔀',
  'tap_to_listen_again': 'Tap to listen again',
  'how_many_were_there': 'How many were there? 🤔',
  'tap_to_listen': 'Tap to listen',
  'hint_text': '🖼️ Hint: @word',
  'objects': 'Objects',
  'pictures': 'Pictures',
  'letters': 'Letters',
  'great_job': 'Great Job!',
  'you_practiced_khmer_letters': 'You practiced Khmer letters!',
  'best_combo': 'Best Combo',
  'answered': 'Answered',
  'new_high_score': 'NEW HIGH SCORE!',
  'play_again': 'Play Again',
  'paused': 'Paused',
  'keep_playing': 'Keep Playing',
  'go_home': 'Go Home',
  'trace_the_answer': 'Trace the answer',
  'pick_the_answer': 'Pick the answer',
  'match_the_cards': 'Match the cards',
  'play_exclamation': 'Play!',
  'combo_streak': '@combo x Streak!',
  'go_exclamation': 'GO!',
  'game_over': 'GAME OVER',
  'coins_earned': 'Coins Earned',
  'best_score': 'Best Score',
  'correct': 'Correct',
  'wrong': 'Wrong',
  'missing': 'Missing',
  'missing_character': 'Missing Character',
  'fill_in_the_missing_character': 'Fill in the missing character',
  'how_many_objects': 'How many objects?',
  'consonant_sprint': 'Consonant Sprint',
  'digit_sprint': 'Digit Sprint',
  'independent_vowel_sprint': 'Independent Vowel Sprint',
  'dependent_vowel_sprint': 'Dependent Vowel Sprint',
  'counting_fun': 'Counting Fun',
  'fill_the_word': 'Fill the Word',
  'math_challenge': 'Math Challenge',
  'question_time': 'Question Time',

  // ===== Quest & Challenge =====
  'daily_quests': 'Daily Quests',
  'my_quest': 'My Quest',
  'all_quests_completed': 'All quests completed!',
  'quests_done_today': '@completed/@total quests done today',
  'daily_streak_count': '@streak streak',
  'coins_count': '@coins coins',
  'no_quests_available': 'No Quests Available',
  'complete_lessons_unlock_quests':
      'Complete more lessons to unlock daily quests.\nCheck back tomorrow!',
  'completed_exclamation': 'Completed!',
  'start_quest': 'Start Quest',

  // Quest Types
  'quest_title_weakest': 'Weakest Character',
  'quest_subtitle_weakest': 'Practice your lowest-accuracy letters',
  'quest_title_mastery': 'Mastery Showcase',
  'quest_subtitle_mastery': 'Show off your best writing!',
  'quest_title_deep_memory': 'Deep Memory',
  'quest_subtitle_deep_memory': 'Refresh a character from long ago',
  'quest_title_recent': 'Recent Characters',
  'quest_subtitle_recent': 'Revisit your latest lesson',
  'quest_subtitle_recent_fallback': "Revisit characters you've learned",
  'quest_title_random': 'Random Review',
  'quest_subtitle_random': "Random mix of everything you've learned",

  // ===== Shop & Avatars =====
  'your_points': 'Your Coins',
  'in_use': 'In Use',
  'owned': 'Owned',
  'use_this_avatar': 'Do you want to use this avatar?',
  'avatar_in_use_desc': 'This avatar is currently set as your profile avatar.',
  'select_avatar': 'Use Avatar',
  'buy_for': 'Unlock for @price',
  'not_enough_points': 'Not enough coins!',
  'need_more_points': 'You need @amount more coins.',
  'your_balance': 'Your balance: @amount coins',
  'points_count': '@count Coins',
  'avatar_default': 'Student',
  'avatar_boar_100': 'Boar',
  'avatar_hippo_100': 'Hippo',
  'shop_subtitle': 'Unlock cute animal friends!',
  'shop_earn_more': 'Keep practicing lessons to earn more coins!',
  'congrats_unlock_title': 'Yay! Unlocked!',
  'congrats_unlock_desc': 'You have successfully unlocked @name!',
  'great_button': 'Awesome!',
  'price': 'Price',
  'your_coins': 'Your Coins',
  'buy_avatar_confirm': 'Unlock this new friend?',
  'avatar_equipped_compliment': 'You look amazing with this avatar!',
  'my_lesson': 'My Lesson',
  'my_writing': 'My Writing',
  'writing_coming_soon': 'Khmer Handwriting Practice feature is coming soon!',
  'statistics': 'Statistics',
  'activities': 'Activities',
  'my_lesson_student_desc': 'Learn Khmer letters & levels',
  'my_lesson_parent_desc': 'Review children courses & progress',
  'my_writing_student_desc': 'Practice tracing & drawing',
  'my_writing_parent_desc': 'View child writing submissions',

  // AI Writing Practice
  'start_practice': 'Start Practice',
  'character': 'Character',
  'repetition': 'Writing',
  'finish': 'Finish',
  'leave_practice': 'Leave Practice?',
  'leave_practice_desc': 'Your current progress will not be saved.',
  'leave': 'Leave',
  'numbers': 'Numbers',
  'selected_count': '@count selected',
  'repeat_count_label': 'Repeat count:',
  'select_characters_tip': 'Select characters to write',
  'hint': 'Hint',
  'hint_coming_soon': 'Hint feature is coming soon!',
  'writing_practice_instruction': 'Look at the guide and write below!',
  'draw_carefully': 'Follow the strokes pattern.',
  'action_learn': 'Learn',
  'action_draw': 'Draw',
  'coins': 'Coins',
  'total_characters': 'Total Characters',
  'repetitions': 'Repetitions',
  'nav_lessons': 'Lessons',
  'nav_games': 'Games',
  'nav_quests': 'Quests',
  'nav_shop': 'Shop',
};
