final Map<String, String> enUS = {
  // ===== General =====
  'hello': 'Hello',
  'welcome': 'Welcome',
  'language': 'Language',
  'back': 'Back',
  'next': 'Next',
  'logout': 'Logout',
  'settings': 'Settings',
  'change_language': 'Change Language',
  'dark_mode': 'Dark Mode',
  'loading': 'Loading...',
  'save': 'Save',
  'edit': 'Edit',
  'delete': 'Delete',
  'update': 'Update',
  'create': 'Create',
  'search': 'Search',
  'filter': 'Filter',
  'sort': 'Sort',
  'refresh': 'Refresh',
  'confirm': 'Confirm',
  'continue': 'Continue',
  'done': 'Done',
  'close': 'Close',
  'ok': 'OK',
  'yes': 'Yes',
  'no': 'No',
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'info': 'Information',
  'attention': 'Attention',

  // ===== Authentication =====
  'enter_your_email_or_phone': 'Enter your email or phone number',
  'enter_your_phone_number': 'Enter your phone number',
  'enter_your_password': 'Enter your password',
  'enter_your_school_id': 'Enter your school ID',
  'phone_number': 'Phone Number',
  'school_id': 'School ID',
  'password': 'Password',
  'forgot_password': 'Forgot Password',
  'login': 'Login',
  'signup': 'Sign Up',
  'register': 'Register',
  'remember_me': 'Remember Me',
  'are_you_sure_you_want_to_logout': 'Are you sure you want to logout?',
  'dont_have_account': "Don't have an account?",
  'already_have_account': 'Already have an account?',
  'confirm_password': 'Confirm Password',
  'reset_password': 'Reset Password',
  'change_password': 'Change Password',

  // ===== OTP Verfication =====
  'otp_verification': 'OTP Verification',
  'enter_verification_code': 'Enter Verification Code',
  'we_sent_code_to': 'We sent a verification code to',
  'didnt_receive_code': "Didn't receive code?",
  'otp_verified_successfully': 'OTP verified successfully',
  'invalid_otp_code': 'Invalid OTP code',
  'verification_failed': 'Verification failed',
  'otp_sent_successfully': "OTP sent successfully",
  'otp_resent_successfully': 'OTP resent successfully',
  'resend': 'Resend',
  'resend_in': 'Resend in',
  'clear': 'Clear',
  'verify': 'Verify',

  // ===== Navigation =====
  'home': 'Home',
  'profile': 'Profile',
  'dashboard': 'Dashboard',
  'menu': 'Menu',
  'notifications': 'Notifications',
  'messages': 'Messages',
  'calendar': 'Calendar',
  'reports': 'Reports',
  'history': 'History',
  'help': 'Help',
  'about': 'About',
  'contact': 'Contact',

  // ===== User & Profile =====
  'user': 'User',
  'users': 'Users',
  'name': 'Name',
  'full_name': 'Full Name',
  'first_name': 'First Name',
  'last_name': 'Last Name',
  'email': 'Email',
  'phone': 'Phone',
  'address': 'Address',
  'birthday': 'Birthday',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'other': 'Other',

  // ===== Status & Actions =====
  'active': 'Active',
  'inactive': 'Inactive',
  'pending': 'Pending',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'approved': 'Approved',
  'rejected': 'Rejected',
  'submitted': 'Submitted',
  'verified': 'Verified',
  'unverified': 'Unverified',
  'enabled': 'Enabled',
  'disabled': 'Disabled',

  // ===== Time & Date =====
  'today': 'Today',
  'yesterday': 'Yesterday',
  'tomorrow': 'Tomorrow',
  'this_week': 'This Week',
  'this_month': 'This Month',
  'this_year': 'This Year',
  'date': 'Date',
  'time': 'Time',
  'date_time': 'Date & Time',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'due_date': 'Due Date',

  // ===== Numbers & Quantities =====
  'zero': 'Zero',
  'one': 'One',
  'two': 'Two',
  'three': 'Three',
  'four': 'Four',
  'five': 'Five',
  'items': 'Items',
  'item': 'Item',
  'total': 'Total',
  'amount': 'Amount',
  'quantity': 'Quantity',
  'count': 'Count',

  // ===== Error & Success Messages =====
  'invalid_credentials': 'Invalid credentials',
  'email_or_phone_required': 'Email or phone number is required',
  'phone_required': "Phone number is required",
  'invalid_email_or_phone': 'Invalid email or phone number',
  'invalid_phone': 'Invalid phone number',
  'school_id_required': 'School ID is required',
  'school_id_min_2_cha': 'School ID must be at least 2 characters',
  'password_required': 'Password is required',
  'password_min_6_cha': 'Password must be at least 6 characters',
  'passwords_do_not_match': 'Passwords do not match',
  'network_error': 'Network error',
  'server_error': 'Server error',
  'unknown_error': 'Unknown error occurred',
  'try_again': 'Please try again',
  'operation_successful': 'Operation successful',
  'operation_failed': 'Operation failed',
  'data_loaded': 'Data loaded successfully',
  'data_saved': 'Data saved successfully',
  'data_updated': 'Data updated successfully',
  'data_deleted': 'Data deleted successfully',

  // ===== Buttons =====
  'cancel': 'Cancel',
  'submit': 'Submit',
  'add': 'Add',
  'remove': 'Remove',
  'view': 'View',
  'view_all': 'View All',
  'view_details': 'View Details',
  'view_more': 'View More',
  'select': 'Select',
  'choose': 'Choose',
  'browse': 'Browse',
  'upload': 'Upload',
  'download': 'Download',
  'print': 'Print',
  'share': 'Share',

  // ===== Forms & Validation =====
  'required': 'Required',
  'optional': 'Optional',
  'invalid_format': 'Invalid format',
  'field_required': 'This field is required',
  'invalid_email': 'Invalid email address',
  'invalid_url': 'Invalid URL',
  'min_length': 'Must be at least @length characters',
  'max_length': 'Must be at most @length characters',
  'passwords_not_match': 'Passwords do not match',

  // ===== School Specific =====
  'student': 'Student',
  'teacher': 'Teacher',
  'parent': "Parent",
  'class': 'Class',
  'grade': 'Grade',
  'homework': 'Homework',
  'assignment': 'Assignment',
  'score': 'Score',
  'result': 'Result',
  'my_course': 'My Course',

  // ===== Course & Progress =====
  'my_courses': 'My Courses',
  'in_progress': 'In Progress',
  'start': 'Start',
  'progress': 'Progress',
  'lessons': 'lessons',
  'stars': 'Stars',
  'remaining': 'Remaining',
  'course_progress': 'Course Progress',
  'continue_learning': 'Continue Learning',
  'begin_course': 'Begin Course',
  'view_course': 'View Course',
  'course_details': 'Course Details',
  'level': 'Level',
  'stage': 'Stage',
  'exercise': 'Exercise',
  'world': 'World',
  'learning_letters': 'Learning Letters',
  'learning_numbers': 'Learning Numbers',
  'khmer_alphabet': 'Khmer Alphabet',
  'math_practice': 'Math Practice',

  // ===== Home & Dashboard =====
  'achievements': 'Achievements',
  'streak': 'Streak',
  'time_spent': 'Time Spent',
  'last_played': 'Last Played',
  'current_level': 'Current Level',
  'next_level': 'Next Level',
  'experience_points': 'Experience Points',

  // ===== Notifications =====
  'no_notifications': 'No Notifications',
  'mark_all_read': 'Mark All as Read',
  'new_assignment': 'New Assignment',
  'achievement_unlocked': 'Achievement Unlocked',
  'level_up': 'Level Up!',

  // ===== Mode Switching =====
  'student_mode': 'Student Mode',
  'parent_mode': 'Parent Mode',
  'switch_to_parent': 'Switch to Parent',
  'switch_to_student': 'Switch to Student',
  'parent_pin': 'Parent PIN',
  'enter_parent_pin': 'Enter Parent PIN',
  'parent_dashboard': 'Parent Dashboard',
  'student_progress': 'Student Progress',

  // ===== PIN / Parent PIN related =====
  'pin': 'PIN',
  'create_pin': 'Create PIN',
  'create_4_digit_pin': 'Create 4-digit PIN',
  'confirm_pin': 'Confirm PIN',
  'confirm_new_pin': 'Confirm new PIN',
  'enter_pin': 'Enter PIN',
  'enter_new_pin': 'Enter new PIN',
  'enter_current_pin': 'Enter current PIN',
  'reenter_pin_to_confirm': 'Re-enter PIN to confirm',
  'pins_do_not_match': 'PINs do not match',
  'invalid_pin': 'Invalid PIN',
  'pin_created': 'PIN created',
  'pin_updated': 'PIN updated',
  'set_pin': 'Set Pin',
  'set_parent_pin_prompt':
      'Would you like to set a 4-digit parent PIN to protect parent mode?',
  'skip_pin_setup': 'Skip PIN setup',
  'dont_ask_again': "Don't ask again",
  'backspace': 'Backspace',
  'enter_digits': 'Please enter 4 digits',
  'update_pin': 'Update PIN',
  'verify_pin': 'Verify PIN',
  'unlock_parent_mode': 'Unlock Parent Mode',
  'success_pin_created': 'Parent PIN has been created successfully',
  'success_pin_updated': 'Parent PIN has been updated successfully',
};
