final Map<String, String> kmKH = {
  // ===== General =====
  'hello': 'សួស្តី',
  'welcome': 'សូមស្វាគមន៍',
  'language': 'ភាសា',
  'back': 'ត្រឡប់ក្រោយ',
  'next': 'បន្ទាប់',
  'logout': 'ចាកចេញ',
  'logout_acc': 'ចាកចេញដោយស្វ័យប្រវត្តិ',
  'settings': 'ការកំណត់ផ្សេងៗ',
  'setting': 'ការកំណត់',
  'change_language': 'ប្តូរភាសា',
  'dark_mode': 'ប្រើម៉ូដងងឹត',
  'loading': 'កំពុងដំណើរការ...',
  'save': 'រក្សាទុក',
  'edit': 'កែសម្រួល',
  'delete': 'លុប',
  'update': 'ធ្វើបច្ចុប្បន្នភាព',
  'create': 'បង្កើត',
  'search': 'ស្វែងរក',
  'filter': 'តម្រង',
  'sort': 'តម្រៀប',
  'refresh': 'ផ្ទុកឡើងវិញ',
  'confirm': 'បញ្ជាក់',
  'confirmed': 'យល់ព្រម',
  'continue': 'បន្ត',
  'done': 'រួចរាល់',
  'close': 'បិទ',
  'ok': 'យល់ព្រម',
  'yes': 'បាទ/ចាស',
  'no': 'ទេ',
  'retry': 'ម្ដងទៀត',
  'skip': 'រំលង',
  'success': 'ជោគជ័យ',
  'error': 'កំហុស',
  'warning': 'ការព្រមាន',
  'info': 'ព័ត៌មាន',
  'attention': 'សម្គាល់',
  'protection': 'សុវត្ថិភាព',
  'accuracy': 'ភាពត្រឹមត្រូវ',
  'best': "ល្អបំផុត",
  'need': "ត្រូវហាត់បន្ថែម",
  'scan': 'ស្កេន QR',

  // ===== Authentication =====
  'enter_your_email_or_phone': 'បញ្ចូលអ៊ីមែល ឬ លេខទូរស័ព្ទរបស់អ្នក',
  'enter_your_phone_number': 'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
  'enter_your_password': 'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក',
  'enter_your_school_id': 'បញ្ចូលលេខសម្គាល់សាលារបស់អ្នក',
  'phone_number': 'លេខទូរស័ព្ទ',
  'school_id': 'លេខសម្គាល់សាលា',
  'password': 'ពាក្យសម្ងាត់',
  'forgot_password': 'ភ្លេចពាក្យសម្ងាត់',
  'login': 'ចូលគណនី',
  'signup': 'ចុះឈ្មោះ',
  'register': 'ចុះឈ្មោះ',
  'remember_me': 'ចងចាំខ្ញុំ',
  'are_you_sure_you_want_to_logout': 'តើអ្នកប្រាកដថាចង់ចាកចេញពីគណនីរបស់អ្នកទេ?',
  'dont_have_account': 'មិនមានគណនី?',
  'already_have_account': 'មានគណនីរួចហើយ?',
  'account_created_successfully': 'បានបង្កើតគណនីដោយជោគជ័យ',
  'confirm_password': 'បញ្ជាក់ពាក្យសម្ងាត់',
  'reset_password': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
  'change_password': 'ផ្លាស់ប្តូរពាក្យសម្ងាត់',
  'current_password': 'លេខសម្ងាត់បច្ចុប្បន្ន',
  'new_password': 'លេខសម្ងាត់ថ្មី',
  'confirm_new_password': 'បញ្ជាក់លេខសម្ងាត់ថ្មី',
  'enter_current_password': 'បញ្ចូលលេខសម្ងាត់បច្ចុប្បន្នរបស់អ្នក',
  'enter_new_password': 'បញ្ចូលលេខសម្ងាត់ថ្មី',
  'confirm_your_new_password': 'បញ្ជាក់លេខសម្ងាត់ថ្មីរបស់អ្នក',
  'update_password': 'ធ្វើបច្ចុប្បន្នភាពលេខសម្ងាត់',
  'password_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពលេខសម្ងាត់ដោយជោគជ័យ',
  'current_password_required': 'ត្រូវការលេខសម្ងាត់បច្ចុប្បន្ន',
  'new_password_required': 'ត្រូវការលេខសម្ងាត់ថ្មី',
  'confirm_password_required': 'សូមបញ្ជាក់លេខសម្ងាត់ថ្មីរបស់អ្នក',

  // ===== OTP Verfication =====
  'otp_verification': 'ការផ្ទៀងផ្ទាត់ OTP',
  'enter_verification_code': 'បញ្ចូលលេខកូដផ្ទៀងផ្ទាត់',
  'we_sent_code_to': 'យើងបានផ្ញើលេខកូដផ្ទៀងផ្ទាត់ទៅកាន់',
  'didnt_receive_code': 'មិនបានទទួលលេខកូដ?',
  'otp_verified_successfully': 'ការផ្ទៀងផ្ទាត់ OTP បានជោគជ័យ',
  'invalid_otp_code': 'លេខកូដ OTP មិនត្រឹមត្រូវ',
  'verification_failed': 'ការផ្ទៀងផ្ទាត់បរាជ័យ',
  'opt_sent_successfuly': "បានផ្ញើ OTP ដោយជោគជ័យ",
  'otp_resent_successfully': 'បានផ្ញើ OTP ឡើងវិញដោយជោគជ័យ',
  'resend': 'ផ្ញើរឡើងវិញ',
  'resend_in': 'ផ្ញើរឡើងវិញនៅពេល',
  'clear': 'លុប',
  'verify': 'ផ្ទៀងផ្ទាត់',

  // ===== Navigation =====
  'home': 'ទំព័រដើម',
  'profile': 'ប្រវត្តិរូប',
  'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'menu': 'ម៉ឺនុយ',
  'notifications': 'ការជូនដំណឹង',
  'messages': 'សារ',
  'calendar': 'ប្រតិទិន',
  'reports': 'របាយការណ៍',
  'history': 'ប្រវត្តិ',
  'help': 'ជំនួយ',
  'about': 'អំពី',
  'contact': 'ទំនាក់ទំនង',

  // ===== User & Profile =====
  'user': 'អ្នកប្រើ',
  'users': 'អ្នកប្រើប្រាស់',
  'name': 'ឈ្មោះ',
  'full_name': 'ឈ្មោះពេញ',
  'first_name': 'គោត្តនាម',
  'last_name': 'ត្រកូល',
  'email': 'អ៊ីមែល',
  'phone': 'ទូរស័ព្ទ',
  'address': 'អាសយដ្ឋាន',
  'birthday': 'ថ្ងៃកំណើត',
  'gender': 'ភេទ',
  'male': 'ប្រុស',
  'female': 'ស្រី',
  'other': 'ផ្សេងៗ',
  'update_information': 'ធ្វើបច្ចុប្បន្នភាពព័ត៌មាន',
  'personal_information': 'ព័ត៌មានផ្ទាល់ខ្លួន',
  'parent_information': 'ព័ត៌មានអាណាព្យាបាល',
  'additional_information': 'ព័ត៌មានបន្ថែម',
  'enter_first_name': 'បញ្ចូលគោត្តនាម',
  'enter_last_name': 'បញ្ចូលនាម',
  'enter_nickname': 'បញ្ចូលឈ្មោះហៅក្រៅ',
  'enter_age': 'បញ្ចូលអាយុ',
  'select_gender': 'ជ្រើសរើសភេទ',
  'date_of_birth': 'ថ្ងៃខែឆ្នាំកំណើត',
  'enter_date_of_birth': 'បញ្ចូលថ្ងៃខែឆ្នាំកំណើត',
  'parent_first_name': 'គោត្តនាមអាណាព្យាបាល',
  'parent_last_name': 'នាមអាណាព្យាបាល',
  'enter_parent_first_name': 'បញ្ចូលឈ្មោះអាណាព្យាបាល',
  'enter_parent_last_name': 'បញ្ចូលត្រគូលអាណាព្យាបាល',
  'enter_address': 'បញ្ចូលអាសយដ្ឋាន',
  'save_changes': 'រក្សាទុកការផ្លាស់ប្តូរ',
  'no_changes_detected': 'មិនមានការផ្លាស់ប្តូរ',
  'profile_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបដោយជោគជ័យ',
  'failed_to_update_profile': 'មិនអាចធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូប',
  'an_error_occurred': 'មានកំហុសមួយបានកើតឡើង',
  'first_name_is_required': 'តម្រូវឲ្យមានគោត្តនាម',
  'first_name_cannot_exceed_100_characters': 'គោត្តនាមមិនអាចលើសពី ១០០ តួអក្សរ',
  'last_name_cannot_exceed_100_characters': 'នាមមិនអាចលើសពី ១០០ តួអក្សរ',
  'age_must_be_a_number': 'អាយុត្រូវតែជាលេខ',
  'age_must_be_between_1_and_100': 'អាយុត្រូវតែចន្លោះពី ១ ទៅ ១០០',
  'gender_must_be_male_female_or_other': 'ភេទត្រូវតែជា ប្រុស ឬ ស្រី',
  'failed_to_load_profile': 'មិនអាចផ្ទុកប្រវត្តិរូប',
  'nickname': 'ឈ្មោះហៅក្រៅ',
  'yyyy-mm-dd': 'ឆ្នាំ-ខែ-ថ្ងៃ',
  'year': 'ឆ្នាំ',
  'require_parent_pin': 'តម្រូវឱ្យមានលេខសម្ងាត់មាតាបិតា',

  // ===== Status & Actions =====
  'active': 'សកម្ម',
  'inactive': 'អសកម្ម',
  'pending': 'កំពុងរង់ចាំ',
  'completed': 'បានបញ្ចប់',
  'cancelled': 'បានបោះបង់',
  'approved': 'បានអនុម័ត',
  'rejected': 'បានបដិសេធ',
  'submitted': 'បានស្នើ',
  'verified': 'បានផ្ទៀងផ្ទាត់',
  'unverified': 'មិនទាន់ផ្ទៀងផ្ទាត់',
  'enabled': 'បានបើក',
  'disabled': 'បានបិទ',

  // ===== Time & Date =====
  'today': 'ថ្ងៃនេះ',
  'yesterday': 'ម្សិលមិញ',
  'tomorrow': 'ថ្ងៃស្អែក',
  'this_week': 'សប្តាហ៍នេះ',
  'this_month': 'ខែនេះ',
  'this_year': 'ឆ្នាំនេះ',
  'date': 'កាលបរិច្ឆេទ',
  'time': 'ពេលវេលា',
  'date_time': 'កាលបរិច្ឆេទ និងពេលវេលា',
  'start_date': 'កាលបរិច្ឆេទចាប់ផ្ដើម',
  'end_date': 'កាលបរិច្ឆេទបញ្ចប់',
  'due_date': 'កាលបរិច្ឆេទនៃការបង់',

  // ===== Numbers & Quantities =====
  'zero': 'សូន្យ',
  'one': 'មួយ',
  'two': 'ពីរ',
  'three': 'បី',
  'four': 'បួន',
  'five': 'ប្រាំ',
  'items': 'ធាតុ',
  'item': 'ធាតុ',
  'total': 'សរុប',
  'amount': 'ចំនួន',
  'quantity': 'បរិមាណ',
  'count': 'រាប់',

  // ===== Error & Success Messages =====
  'invalid_credentials': 'ព័ត៌មានសម្ងាត់មិនត្រឹមត្រូវ',
  'email_or_phone_required': 'ត្រូវការអ៊ីមែល ឬ លេខទូរស័ព្ទ',
  'phone_required': "ត្រូវការលេខទូរស័ព្ទ",
  'invalid_email_or_phone': 'អ៊ីមែល ឬ លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
  'invalid_phone': 'លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
  'school_id_required': 'ត្រូវការលេខសម្គាល់សាលា',
  'school_id_min_2_cha': 'លេខសម្គាល់សាលាត្រូវមានយ៉ាងតិច ២ តួអក្សរ',
  'password_required': 'ត្រូវការពាក្យសម្ងាត់',
  'password_min_6_cha': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ',
  'passwords_do_not_match': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',
  'network_error': 'កំហុសបណ្តាញ',
  'server_error': 'កំហុសម៉ាស៊ីនបម្រើ',
  'unknown_error': 'មានកំហុសមិនស្គាល់',
  'try_again': 'សូមព្យាយាមម្តងទៀត',
  'operation_successful': 'ប្រតិបត្តិការជោគជ័យ',
  'operation_failed': 'ប្រតិបត្តិការបរាជ័យ',
  'data_loaded': 'ទិន្នន័យបានផ្ទុកដោយជោគជ័យ',
  'data_saved': 'ទិន្នន័យបានរក្សាទុកដោយជោគជ័យ',
  'data_updated': 'ទិន្នន័យបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ',
  'data_deleted': 'ទិន្នន័យបានលុបដោយជោគជ័យ',
  'image_updated': "រូបភាពបានដោយជោគជ័យ",
  'image_too_large': "ទំហំរូបភាពធំពេក។ សូមជ្រើសរើសរូបភាពដែលតូចជាង 2MB",

  // ===== Buttons =====
  'cancel': 'បោះបង់',
  'submit': 'យល់ព្រម',
  'add': 'បន្ថែម',
  'remove': 'ដកចេញ',
  'view': 'មើល',
  'view_all': 'មើលទាំងអស់',
  'view_details': 'មើលព័ត៌មានលម្អិត',
  'view_more': 'មើលបន្ថែម',
  'select': 'ជ្រើសរើស',
  'choose': 'ជ្រើសរើស',
  'browse': 'រកមើល',
  'upload': 'ផ្ទុកឡើង',
  'download': 'ទាញយក',
  'print': 'បោះពុម្ព',
  'share': 'ចែករំលែក',

  // ===== Forms & Validation =====
  'required': 'តម្រូវឲ្យមាន',
  'optional': 'មិនចាំបាច់',
  'invalid_format': 'ទម្រង់មិនត្រឹមត្រូវ',
  'field_required': 'ត្រូវការបំពេញព័ត៌មាន',
  'invalid_email': 'អ៊ីមែលមិនត្រឹមត្រូវ',
  'invalid_url': 'URL មិនត្រឹមត្រូវ',
  'min_length': 'ត្រូវតែមានយ៉ាងតិច @length តួអក្សរ',
  'max_length': 'មិនត្រូវលើសពី @length តួអក្សរ',
  'passwords_not_match': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',
  'fill_all_fields_correctly': 'សូមបំពេញគ្រប់ផ្នែកដោយត្រឹមត្រូវ',
  'fill_all_fields': 'សូមបំពេញគ្រប់ផ្នែក',

  // ===== School Specific =====
  'student': 'សិស្ស',
  'parent': "អាណាព្យាបាល",
  'teacher': 'គ្រូ',
  'class': 'ថ្នាក់',
  'grade': 'ចំណាត់ថ្នាក់',
  'homework': 'កិច្ចការផ្ទះ',
  'assignment': 'កិច្ចការ',
  'score': 'ពិន្ទុ',
  'result': 'លទ្ធផល',
  'my_course': 'វគ្គសិក្សារបស់ខ្ញុំ',
  'classroom': 'ថ្នាក់រៀន',
  'no_classroom_yet': 'មិនទាន់មានថ្នាក់រៀនទេ',
  'join_classroom_desc':
      'ចូលរួមថ្នាក់រៀនរបស់កូន ដើម្បីមើលមិត្តរួមថ្នាក់ និងវឌ្ឍនភាព។',
  'enter_code': 'បញ្ចូលកូដ',
  'example_code': 'ឧទាហរណ៍៖ SCH-ABC12345',
  'join': 'ចូលរួម',
  'joined': 'បានចូលរួម',
  'classmates': 'មិត្តរួមថ្នាក់',
  'no_classmates': 'មិនមានមិត្តរួមថ្នាក់',

  // ===== Course & Progress =====
  'my_courses': 'វគ្គសិក្សារបស់ខ្ញុំ',
  'in_progress': 'កំពុងរៀន',
  'start': 'ចាប់ផ្តើម',
  "locked": 'ចាក់សោ',
  'level_locked': "វគ្គនេះត្រូវបានចាក់សោរ 🔒",
  'progress': 'វឌ្ឍនភាព',
  'lessons': 'មេរៀន',
  'stars': 'ផ្កាយ',
  'remaining': 'នៅសល់',
  'course_progress': 'វឌ្ឍនភាពវគ្គសិក្សា',
  'continue_learning': 'បន្តការរៀន',
  'begin_course': 'ចាប់ផ្តើមវគ្គសិក្សា',
  'view_course': 'មើលវគ្គសិក្សា',
  'course_details': 'ព័ត៌មានលម្អិតវគ្គសិក្សា',
  'level': 'កម្រិត',
  'stage': 'ដំណាក់កាល',
  'exercise': 'លំហាត់',
  'world': 'ពិភព',
  'learning_letters': 'រៀនអក្សរ',
  'learning_numbers': 'រៀនលេខ',
  'khmer_alphabet': 'អក្សរខ្មែរ',
  'math_practice': 'លំហាត់គណិតវិទ្យា',

  // ===== Home & Dashboard =====
  'achievements': 'សមិទ្ធផល',
  'streak': 'ដំណើរបន្ត',
  'time_spent': 'ពេលវេលាបានប្រើ',
  'last_played': 'លេងចុងក្រោយ',
  'current_level': 'កម្រិតបច្ចុប្បន្ន',
  'next_level': 'កម្រិតបន្ទាប់',
  'experience_points': 'ពិន្ទុបទពិសោធន៍',
  'summary': 'របាយការណ៍សង្ខេប',
  'summary_daily': 'សង្ខេបថ្ងៃនេះ',
  'lesson_completed': "មេរៀនបានហាត់",
  'summary_weekly': 'សង្ខេបប្រចាំសប្ដាហ៍',
  'mastered': 'ធ្វើបានល្អ',
  'review': 'ត្រូវការអនុវត្តបន្ថែម',
  'practice_days': 'ថ្ងៃដែលបានអនុវត្ត',

  // ===== Notifications =====
  'no_notifications': 'គ្មានការជូនដំណឹង',
  'mark_all_read': 'សម្គាល់ថាបានអានទាំងអស់',
  'new_assignment': 'កិច្ចការថ្មី',
  'achievement_unlocked': 'បានបើកសមិទ្ធផល',
  'level_up': 'ត្រឡប់កម្រិត!',

  // ===== Mode Switching =====
  'student_mode': 'ម៉ូដសិស្ស',
  'parent_mode': 'ម៉ូដអាណាព្យាបាល',
  'switch_to_parent': 'ប្តូរទៅអាណាព្យាបាល',
  'switch_to_student': 'ប្តូរទៅសិស្ស',
  'parent_pin': 'កូដអាណាព្យាបាល',
  'enter_parent_pin': 'បញ្ចូលកូដអាណាព្យាបាល',
  'parent_dashboard': 'ផ្ទាំងអាណាព្យាបាល',
  'student_progress': 'វឌ្ឍនភាពសិស្ស',

  // ===== PIN / Parent PIN related =====
  'pin': 'លេខសម្ងាត់',
  'create_pin': 'បង្កើតលេខសម្ងាត់',
  'create_4_digit_pin': 'បង្កើតលេខសម្ងាត់ 4 ខ្ទង់',
  'confirm_pin': 'បញ្ជាក់លេខសម្ងាត់',
  'confirm_new_pin': 'បញ្ជាក់លេខសម្ងាត់ថ្មី',
  'enter_pin': 'បញ្ចូលលេខសម្ងាត់',
  'enter_new_pin': 'បញ្ចូលលេខសម្ងាត់ថ្មី',
  'enter_current_pin': 'បញ្ចូលលេខសម្ងាត់បច្ចុប្បន្ន',
  'reenter_pin_to_confirm': 'សូមបញ្ចូលឡើងវិញដើម្បីបញ្ជាក់',
  'pins_do_not_match': 'លេខសម្ងាត់មិនត្រូវគ្នា',
  'invalid_pin': 'លេខសម្ងាត់មិនត្រឹមត្រូវ',
  'pin_created': 'បានបង្កើតលេខសម្ងាត់ហើយ',
  'pin_updated': 'បានធ្វើបច្ចុប្បន្នភាពលេខសម្ងាត់',
  'set_pin': 'បញ្ចូលលេខសម្ងាត់',
  'set_parent_pin_prompt':
      'តើអ្នកចង់កំណត់លេខសម្ងាត់ 4 ខ្ទង់សម្រាប់ការពារម៉ូដអាណាព្យាបាលទេ?',
  'skip_pin_setup': 'លើកលែងការកំណត់លេខសម្ងាត់',
  'dont_ask_again': 'កុំសួរម្ដងទៀត',
  'backspace': 'លុបទាក្សរ',
  'enter_digits': 'សូមបញ្ចូលលេខ 4 ខ្ទង់',
  'update_pin': 'ប្តូរលេខសម្ងាត់',
  'verify_pin': 'ផ្ទៀងផ្ទាត់លេខសម្ងាត់',
  'unlock_parent_mode': 'ដោះសោម៉ូដអាណាព្យាបាល',
  'success_pin_created': 'បានបង្កើតកូដអាណាព្យាបាលដោយជោគជ័យ',
  'success_pin_updated': 'បានធ្វើបច្ចុប្បន្នភាពកូដអាណាព្យាបាលដោយជោគជ័យ',
  'update_parent_pin': 'បង្កើតកូដអាណាព្យាបាលថ្មី',
  'change_parent_pin': 'ប្ដូរកូដអាណាព្យាបាល',
  'enter_current_pin_to_update': 'បញ្ចូលកូដបច្ចុប្បន្នដើម្បីបង្កើតថ្មី',
  'create_new_pin': 'បង្កើតកូដថ្មី',
  'parent_pin_updated': 'កូដអាណាព្យាបាលត្រូវបានបង្កើតថ្មី',
  'parent_pin_created': 'កូដអាណាព្យាបាលត្រូវបានបង្កើត',
  'pin_setup_complete': 'ការកំណត់កូដបានបញ្ចប់',
  'pin_verification_successful': 'ការផ្ទៀងផ្ទាត់កូដជោគជ័យ',
  'enter_4_digit_pin': 'បញ្ចូលកូដ 4 ខ្ទង់',
  're_enter_4_digit_pin': 'បញ្ចូលកូដ 4 ខ្ទង់ម្តងទៀត',
  'pin_must_be_4_digits': 'កូដត្រូវតែមាន 4 ខ្ទង់',
  'pin_changed_successfully': 'កូដត្រូវបានប្ដូរដោយជោគជ័យ',
  'current_pin_incorrect': 'កូដបច្ចុប្បន្នមិនត្រឹមត្រូវ',
  'pin_setup_required': 'តម្រូវឲ្យមានការកំណត់កូដ',
  'pin_verification_required': 'តម្រូវឲ្យមានការផ្ទៀងផ្ទាត់កូដ',
  'create_your_pin': 'បង្កើតកូដរបស់អ្នក',
  'confirm_your_pin': 'បញ្ជាក់កូដរបស់អ្នក',
  'verify_your_pin': 'ផ្ទៀងផ្ទាត់កូដរបស់អ្នក',

  // ===== QR Scanner =====
  'scan_qr_title': 'ស្កេន QR',
  'flash_on': 'បើកភ្លើង',
  'flash_off': 'បិទភ្លើង',
  'gallery': 'វិចិត្រសាល',
  'align_qr_hint': 'ដាក់ QR នៅក្នុងប្រអប់',
  'no_qr_found': 'រកមិនឃើញ QR ក្នុងរូបនេះទេ',
  'invalid_qr': 'QR មិនត្រឹមត្រូវ',
  'scan_failed': 'មិនអាចស្កេនបានទេ',
  'flash_unavailable': 'មិនអាចប្រើភ្លើងលើឧបករណ៍នេះបានទេ',

  // ===== Report / Parent Report =====
  'report_detail_title': 'របាយការណ៍លម្អិត',
  'monthly_summary': 'សង្ខេបប្រចាំខែ',
  'total_exercises': 'លំហាត់សរុប',
  'total_study_time': 'ពេលវេលាសិក្សាសរុប',
  'weekly_exercises_in_month': 'លំហាត់ប្រចាំសប្ដាហ៍ (ក្នុងខែនេះ)',
  'character_performance': 'សមត្ថភាពតាមអក្សរ',
  'week': 'សប្ដាហ៍',
  'attempts': 'លើក',
  'times': 'លើក',

  // ===== Summary Page =====
  'summary_perfect': 'ឆ្លើយបានត្រឹមត្រូវ',
  'summary_great': 'អស្ចារ្យណាស់!',
  'summary_good_try': 'ព្យាយាមល្អណាស់! បន្តហាត់បន្តិចទៀត!',

  // ===== Offline =====
  'offline': 'អុហ្វឡាញ',
  'no_internet_connection': 'គ្មានការតភ្ជាប់អ៊ីនធឺណិត',
  'internet_required_to_continue':
      'កម្មវិធីនេះត្រូវការការតភ្ជាប់អ៊ីនធឺណិតដើម្បីបន្ត។\nសូមពិនិត្យ Wi-Fi ឬទិន្នន័យទូរស័ព្ទរបស់អ្នក។',
  'open_settings': 'បើកការកំណត់',
  'tip_public_wifi_sign_in':
      'គន្លឹះ៖ ប្រសិនបើអ្នកប្រើ Wi-Fi សាធារណៈ អ្នកអាចត្រូវចូល (Sign in) ជាមុនសិន។',
  'still_offline': 'នៅតែគ្មានអ៊ីនធឺណិត។',
};
