final Map<String, String> kmKH = {
  // ===== General =====
  'hello': 'សួស្តី',
  'welcome': 'សូមស្វាគមន៍',
  'language': 'ភាសា',
  'back': 'ត្រឡប់ក្រោយ',
  'next': 'បន្ទាប់',
  'logout': 'ចាកចេញ',
  'settings': 'ការកំណត់',
  'change_language': 'ប្តូរភាសា',
  'dark_mode': 'ប្រើម៉ូដងងឹត',
  'loading': 'កំពុងដំណើរការ...',
  'save': 'រក្សាទុក',
  'edit': 'កែសម្រួល',
  'delete': 'លុប',
  'update': 'ធ្វើបច្ចុប្បន្នភាព',
  'create': 'បង្កើត',
  'search': 'ស្វែងរក',
  'filter': 'តម្រង',
  'sort': 'តម្រៀប',
  'refresh': 'ផ្ទុកឡើងវិញ',
  'confirm': 'បញ្ជាក់',
  'continue': 'បន្ត',
  'done': 'រួចរាល់',
  'close': 'បិទ',
  'ok': 'យល់ព្រម',
  'yes': 'បាទ/ចាស',
  'no': 'ទេ',
  'success': 'ជោគជ័យ',
  'error': 'កំហុស',
  'warning': 'ការព្រមាន',
  'info': 'ព័ត៌មាន',
  'attention': 'សម្គាល់',

  // ===== Authentication =====
  'enter_your_email_or_phone': 'បញ្ចូលអ៊ីមែល ឬ លេខទូរស័ព្ទរបស់អ្នក',
  'enter_your_phone_number': 'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
  'enter_your_password': 'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក',
  'enter_your_school_id': 'បញ្ចូលលេខសម្គាល់សាលារបស់អ្នក',
  'phone_number': 'លេខទូរស័ព្ទ',
  'school_id': 'លេខសម្គាល់សាលា',
  'password': 'ពាក្យសម្ងាត់',
  'forgot_password': 'ភ្លេចពាក្យសម្ងាត់',
  'login': 'ចូលគណនី',
  'signup': 'ចុះឈ្មោះ',
  'register': 'ចុះឈ្មោះ',
  'remember_me': 'ចងចាំខ្ញុំ',
  'are_you_sure_you_want_to_logout': 'តើអ្នកប្រាកដថាចង់ចាកចេញពីគណនីរបស់អ្នកទេ?',
  'dont_have_account': 'មិនមានគណនី?',
  'already_have_account': 'មានគណនីរួចហើយ?',
  'confirm_password': 'បញ្ជាក់ពាក្យសម្ងាត់',
  'reset_password': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
  'change_password': 'ប្តូរពាក្យសម្ងាត់',

  // ===== OTP Verfication =====
  'otp_verification': 'ការផ្ទៀងផ្ទាត់ OTP',
  'enter_verification_code': 'បញ្ចូលលេខកូដផ្ទៀងផ្ទាត់',
  'we_sent_code_to': 'យើងបានផ្ញើលេខកូដផ្ទៀងផ្ទាត់ទៅកាន់',
  'didnt_receive_code': 'មិនបានទទួលលេខកូដ?',
  'otp_verified_successfully': 'ការផ្ទៀងផ្ទាត់ OTP បានជោគជ័យ',
  'invalid_otp_code': 'លេខកូដ OTP មិនត្រឹមត្រូវ',
  'verification_failed': 'ការផ្ទៀងផ្ទាត់បរាជ័យ',
  'opt_sent_successfuly': "បានផ្ញើ OTP ដោយជោគជ័យ",
  'otp_resent_successfully': 'បានផ្ញើ OTP ឡើងវិញដោយជោគជ័យ',
  'resend': 'ផ្ញើរឡើងវិញ',
  'resend_in': 'ផ្ញើរឡើងវិញនៅពេល',
  'clear': 'លុប',
  'verify': 'ផ្ទៀងផ្ទាត់',

  // ===== Navigation =====
  'home': 'ទំព័រដើម',
  'profile': 'ប្រវត្តិរូប',
  'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'menu': 'ម៉ឺនុយ',
  'notifications': 'ការជូនដំណឹង',
  'messages': 'សារ',
  'calendar': 'ប្រតិទិន',
  'reports': 'របាយការណ៍',
  'history': 'ប្រវត្តិ',
  'help': 'ជំនួយ',
  'about': 'អំពី',
  'contact': 'ទំនាក់ទំនង',

  // ===== User & Profile =====
  'user': 'អ្នកប្រើ',
  'users': 'អ្នកប្រើប្រាស់',
  'name': 'ឈ្មោះ',
  'full_name': 'ឈ្មោះពេញ',
  'first_name': 'គោត្តនាម',
  'last_name': 'នាម',
  'email': 'អ៊ីមែល',
  'phone': 'ទូរស័ព្ទ',
  'address': 'អាសយដ្ឋាន',
  'birthday': 'ថ្ងៃកំណើត',
  'gender': 'ភេទ',
  'male': 'ប្រុស',
  'female': 'ស្រី',
  'other': 'ផ្សេងៗ',

  // ===== Status & Actions =====
  'active': 'សកម្ម',
  'inactive': 'អសកម្ម',
  'pending': 'កំពុងរង់ចាំ',
  'completed': 'បានបញ្ចប់',
  'cancelled': 'បានបោះបង់',
  'approved': 'បានអនុម័ត',
  'rejected': 'បានបដិសេធ',
  'submitted': 'បានស្នើ',
  'verified': 'បានផ្ទៀងផ្ទាត់',
  'unverified': 'មិនទាន់ផ្ទៀងផ្ទាត់',
  'enabled': 'បានបើក',
  'disabled': 'បានបិទ',

  // ===== Time & Date =====
  'today': 'ថ្ងៃនេះ',
  'yesterday': 'ម្សិលមិញ',
  'tomorrow': 'ថ្ងៃស្អែក',
  'this_week': 'សប្តាហ៍នេះ',
  'this_month': 'ខែនេះ',
  'this_year': 'ឆ្នាំនេះ',
  'date': 'កាលបរិច្ឆេទ',
  'time': 'ពេលវេលា',
  'date_time': 'កាលបរិច្ឆេទ និងពេលវេលា',
  'start_date': 'កាលបរិច្ឆេទចាប់ផ្ដើម',
  'end_date': 'កាលបរិច្ឆេទបញ្ចប់',
  'due_date': 'កាលបរិច្ឆេទនៃការបង់',

  // ===== Numbers & Quantities =====
  'zero': 'សូន្យ',
  'one': 'មួយ',
  'two': 'ពីរ',
  'three': 'បី',
  'four': 'បួន',
  'five': 'ប្រាំ',
  'items': 'ធាតុ',
  'item': 'ធាតុ',
  'total': 'សរុប',
  'amount': 'ចំនួន',
  'quantity': 'បរិមាណ',
  'count': 'រាប់',

  // ===== Error & Success Messages =====
  'invalid_credentials': 'ព័ត៌មានសម្ងាត់មិនត្រឹមត្រូវ',
  'email_or_phone_required': 'ត្រូវការអ៊ីមែល ឬ លេខទូរស័ព្ទ',
  'invalid_email_or_phone': 'អ៊ីមែល ឬ លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
  'school_id_required': 'ត្រូវការលេខសម្គាល់សាលា',
  'school_id_min_2_cha': 'លេខសម្គាល់សាលាត្រូវមានយ៉ាងតិច ២ តួអក្សរ',
  'password_required': 'ត្រូវការពាក្យសម្ងាត់',
  'password_min_6_cha': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ',
  'passwords_do_not_match': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',
  'network_error': 'កំហុសបណ្តាញ',
  'server_error': 'កំហុសម៉ាស៊ីនបម្រើ',
  'unknown_error': 'មានកំហុសមិនស្គាល់',
  'try_again': 'សូមព្យាយាមម្តងទៀត',
  'operation_successful': 'ប្រតិបត្តិការជោគជ័យ',
  'operation_failed': 'ប្រតិបត្តិការបរាជ័យ',
  'data_loaded': 'ទិន្នន័យបានផ្ទុកដោយជោគជ័យ',
  'data_saved': 'ទិន្នន័យបានរក្សាទុកដោយជោគជ័យ',
  'data_updated': 'ទិន្នន័យបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ',
  'data_deleted': 'ទិន្នន័យបានលុបដោយជោគជ័យ',

  // ===== Buttons =====
  'cancel': 'បោះបង់',
  'submit': 'យល់ព្រម',
  'add': 'បន្ថែម',
  'remove': 'ដកចេញ',
  'view': 'មើល',
  'view_all': 'មើលទាំងអស់',
  'view_details': 'មើលព័ត៌មានលម្អិត',
  'view_more': 'មើលបន្ថែម',
  'select': 'ជ្រើសរើស',
  'choose': 'ជ្រើសរើស',
  'browse': 'រកមើល',
  'upload': 'ផ្ទុកឡើង',
  'download': 'ទាញយក',
  'print': 'បោះពុម្ព',
  'share': 'ចែករំលែក',

  // ===== Forms & Validation =====
  'required': 'តម្រូវឲ្យមាន',
  'optional': 'មិនចាំបាច់',
  'invalid_format': 'ទម្រង់មិនត្រឹមត្រូវ',
  'field_required': 'ត្រូវការបំពេញព័ត៌មាន',
  'invalid_email': 'អ៊ីមែលមិនត្រឹមត្រូវ',
  'invalid_phone': 'លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
  'invalid_url': 'URL មិនត្រឹមត្រូវ',
  'min_length': 'ត្រូវតែមានយ៉ាងតិច @length តួអក្សរ',
  'max_length': 'មិនត្រូវលើសពី @length តួអក្សរ',
  'passwords_not_match': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',

  // ===== School Specific =====
  'student': 'សិស្ស',
  'teacher': 'គ្រូ',
  'class': 'ថ្នាក់',
  'grade': 'ចំណាត់ថ្នាក់',
  'homework': 'កិច្ចការផ្ទះ',
  'assignment': 'កិច្ចការ',
  'score': 'ពិន្ទុ',
  'result': 'លទ្ធផល',
};
